---
- name: Configure VLAN and assign port on Cisco Switch
  hosts: cisco_switches
  gather_facts: no
  connection: network_cli

  vars:
    vlan_id: 20
    vlan_name: Ansible_Assign2
    user_interface: GigabitEthernet0/1

  tasks:
    - name: Create VLAN
      cisco.ios.ios_vlan:
        vlan_id: "{{ vlan_id }}"
        name: "{{ vlan_name }}"
        state: present

    - name: Assign interface to VLAN
      cisco.ios.ios_l2_interface:
        name: "{{ user_interface }}"
        mode: access
        access_vlan: "{{ vlan_id }}"
        state: present

    - name: Enable interface
      cisco.ios.ios_interface:
        name: "{{ user_interface }}"
        enabled: true
        state: up
